# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: '/Research/'
    weight: 10
  - name: Team
    url: '/Team/'
    weight: 20
  - name: Publications
    url: '/Publications/'
    weight: 30
  - name: News
    url: '/News/'
    weight: 40
  - name: Blog
    url: '/Blog/'
    weight: 50